<a href="https://colab.research.google.com/github/Wikanes-k/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as  np #package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

#Numpy Array

##สร้าง numpy array (matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]]) 
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

###สร้าง matrix เริ่มต้น (zeros, ones)

In [9]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((5,6))
np_200

array([[200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200.]])

##สร้าง matrix random

In [13]:
np.random.randn(5,5) #random เลจมาจาก normal distribution ที่มี mu=0 std=1

array([[ 0.00424959,  0.84895418,  0.83417566,  0.60915189, -0.90977597],
       [-0.08850185,  0.43311931, -1.33533274, -0.14469858,  0.68977907],
       [-0.2434641 , -0.50986025,  0.52745005,  0.47039225, -0.29596791],
       [-0.86856127,  0.64899406, -0.61673052,  0.92873051,  1.35345392],
       [-1.50582927,  0.38241608,  0.02816371,  1.45176184,  0.52283917]])

In [15]:
2+(5*np.random.randn(3,3)) #random เลจมาจาก normal distribution ที่มี mu=2 std=5

array([[ 6.52196852, -0.29341539, -2.58510459],
       [ 5.01836176,  1.52646965, -0.23518108],
       [-1.6088014 ,  6.52986263,  5.27299481]])

In [16]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4*5)

array([[ 8,  8,  7, 10,  9],
       [10,  8,  9,  7, 10],
       [ 8,  5,  9,  8,  8],
       [ 5,  9,  8,  7,  8]])